### ISSUE TITLE
"local_settings.py" missing OGC login and logout endpoint entries

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode-workshop#12]
"local_settings.py" of the vagrant VM should declare the two entries

        'LOGIN_ENDPOINT': 'j_spring_oauth2_geonode_login',
        'LOGOUT_ENDPOINT': 'j_spring_oauth2_geonode_logout',

on "OGC_SERVER" array, otherwise GeoNode will throw an error when trying to logout.

**Comment by francbartoli** [comment]
@afabiani correct! I think the packaging is missing this little piece.
