### ISSUE TITLE
Layers and Maps list are not visibile from GeoNode gui, but the counter is updated correctly

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode-workshop#15]
Explore Layers and Maps do not show any record.
This may depend from the many JavaScript issues thrown due to 404 errors on static folder.

Maybe an Apache2 configuration issue.

![image](https://cloud.githubusercontent.com/assets/1278021/22503499/4d55f0f6-e872-11e6-8d81-bb95d5b8281f.png)

**Comment by afabiani** [comment]
[UPDATE]: the static libraries are not loaded due to an incorrect encoding

http://localhost:8001/static/lib/js/esri-leaflet.js%3Fv%3D2.5.10

should be 

http://localhost:8001/static/lib/js/esri-leaflet.js?v=2.5.10

instead.

**Comment by simod** [comment]
was also an autocomplete packaging issue. Released a new one and issued a PR for the versions of the libraries.
