### ISSUE TITLE
ImportError: No module named geonode.settings

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode-workshop#5]
Error thrown after geonode install from repo

sudo apt-get install geonode

**Comment by afabiani** [comment]
It seems like it is failing if your locale is not correctly set. I fixed this by running the following commands:

sudo locale-gen en_US
sudo locale-gen en_US.UTF-8
sudo locale-gen it_IT.ISO-8859-1
sudo locale-gen it_IT.UTF-8
sudo locale-gen it_IT.ISO-8859-15@euro

sudo update-locale

sudo vim /etc/default/locale

LANG=en_US.UTF-8
LANGUAGE="en_US:en"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"

sudo dpkg-reconfigure geonode

**Comment by simod** [comment]
for me:
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

was enough to make the installation go fine

**Comment by riccardoklinger** [comment]
reinstalling pip solved the issue on my ubuntu 16.04 as an old version of pip was installed (8.1.1.)
